version: 2

sources:
   - name: gz_raw_sales
     database: project-dbt-aline
     schema: gz_raw_data
     loader: bigquery
     description: ...
     freshness:
       warn_after: {count: .., period: ..}
       error_after: {count: .., period: ..}
     tables:
       - name: sales
         identifier: raw_gz_sales
       - name: product
         identifier: raw_gz_product
       - name: ship
         identifier: raw_gz_ship 